#!/usr/bin/env bats

#  Script: hhs-text.bats
# Purpose: hhs-text tests.
# Created: Feb 16, 2025
#  Author: Generated by ChatGPT (gpt-5-codex)
# License: Please refer to <https://opensource.org/licenses/MIT>
#

load test_helper
load "${HHS_FUNCTIONS_DIR}/hhs-text.bash"
load_bats_libs

# TC - 1
@test "when-highlighting-text-from-file-then-matching-line-is-colored" {
  local input_file
  input_file="${BATS_TEST_TMPDIR}/highlight.txt"

  cat <<'EOF' >"${input_file}"
alpha
Beta
gamma
EOF

  run __hhs_highlight "beta" "${input_file}"

  assert_success
  assert_output --partial $'\e['
  assert_output --partial 'Beta'
  refute_output --partial 'alpha'
  refute_output --partial 'gamma'
}

# TC - 2
@test "when-highlighting-with-grep-flags-then-leading-options-are-forwarded" {
  local input_file
  input_file="${BATS_TEST_TMPDIR}/highlight-flags.txt"

  cat <<'EOF' >"${input_file}"
alpha
Beta
gamma
EOF

  run __hhs_highlight -i "beta" "${input_file}"

  assert_success
  assert_output --partial $'\e['
  assert_output --partial 'Beta'
  refute_output --partial 'alpha'
  refute_output --partial 'gamma'
}

# TC - 3
@test "when-jq-is-available-then-json-print-uses-it" {
  ensure_json_print
  run command -v jq
  assert_success
  run __hhs_json_print '{"foo": 1, "bar": 2}'

  assert_success
  assert_output --partial '"bar": 2'
  assert_output --partial '"foo": 1'
}

# TC - 4
@test "when-xmllint-is-available-then-xml-print-uses-it" {
  # Ensure xmllint is installed
  if ! command -v xmllint >/dev/null; then
    skip "xmllint is not installed"
  fi
  run command -v xmllint
  assert_success

  # Run the function with unformatted XML
  run __hhs_xml_print '<root><child>1</child><child>2</child></root>'
  assert_success

  assert_output --partial '<root>'
  assert_output --partial '<child>1</child>'
  assert_output --partial '<child>2</child>'
}

# TC - 5
@test "when-converting-string-to-ascii-then-numeric-representations-are-returned" {
  run __hhs_ascof 'Hi'

  assert_success
  assert_output --partial 'Dec: 072 105'
  assert_output --partial 'Hex: 48 69'
  assert_output --partial 'Str: Hi'
}

# TC - 6
@test "when-converting-valid-unicode-then-all-representations-are-printed" {
  run __hhs_utoh f123

  assert_success
  assert_output --partial "[Unicode:'\\uf123']"
  assert_output --partial 'Hex => \xef\x84\xa3'
  assert_output --partial 'Icn => '
  assert_output --partial 'Oct => \357\204\243'
}
