[server]
address = "127.0.0.1"
enableCORS = true
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#bd93f9"
backgroundColor = "#282a36"
secondaryBackgroundColor = "#44475a"
textColor = "#f8f8f2"
linkColor = "#8be9fd"
borderColor = "#6272a4"
dataframeBorderColor = "#6272a4"
dataframeHeaderBackgroundColor = "#44475a"
codeBackgroundColor = "#21222c"
baseRadius = "0.4rem"
buttonRadius = "0.25rem"
showWidgetBorder = true
showSidebarBorder = true
